export function PrivacyPolicy() {
  return (
    <div className="rich-text-block-2 w-richtext">
      <h1 className="heading-4-center-black">Privacy Policy</h1>
      <h4>Last updated: December 12, 2023</h4>
      <h4>
        This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the
        Service and tells You about Your privacy rights and how the law protects You.
      </h4>
      <h4>
        We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of
        information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the{' '}
        <a href="https://www.freeprivacypolicy.com/free-privacy-policy-generator/" target="_blank" rel="noreferrer">
          Free Privacy Policy Generator
        </a>
        .
      </h4>
      <h4>Interpretation and Definitions</h4>
      <h4>Interpretation</h4>
      <h4>
        The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions
        shall have the same meaning regardless of whether they appear in singular or in plural.
      </h4>
      <h4>Definitions</h4>
      <h4>For the purposes of this Privacy Policy:</h4>
      <ul role="list" className="list">
        <li>
          <strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.
        </li>
        <li>
          <strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where
          &quot;control&quot; means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election
          of directors or other managing authority.
        </li>
        <li>
          <strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this
          Agreement) refers to Fondation Massa, Rue de Chantepoulet 10, c/o Calliopée Sàrl, 1201 Genève.
        </li>
        <li>
          <strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website,
          containing the details of Your browsing history on that website among its many uses.
        </li>
        <li>
          <strong>Country</strong> refers to: Switzerland
        </li>
        <li>
          <strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.
        </li>
        <li>
          <strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.
        </li>
        <li>
          <strong>Service</strong> refers to the Website.
        </li>
        <li>
          <strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.
        </li>
        <li>
          <strong>Third-party Social Media Service</strong> refers to any website or any social network website through which a User can log
          in or create an account to use the Service.
        </li>
        <li>
          <strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service
          infrastructure itself (for example, the duration of a page visit).
        </li>
        <li>
          <strong>Website</strong> refers to Massa Foundation, accessible from{' '}
          <a href="https://massa.foundation/" target="_blank" rel="noreferrer">
            https://massa.foundation
          </a>
        </li>
        <li>
          <strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which
          such individual is accessing or using the Service, as applicable.
        </li>
      </ul>
      <h4>Collecting and Using Your Personal Data</h4>
      <h4>Types of Data Collected</h4>
      <h4>Personal Data</h4>
      <h4>While using Our Service, We may ask You to provide Us with certain personally identifiable information:</h4>
      <ul role="list" className="list">
        <li>Email address</li>
        <li>Usage Data</li>
      </ul>
      <h4>Usage Data</h4>
      <h4>Usage Data is collected automatically when using the Service.</h4>
      <h4>
        Usage Data may include information such as Your Device&apos;s IP address, browser type/version, the pages visited, time and date of
        visit, time spent, unique device identifiers and other diagnostic data. When accessing via mobile, we may collect device type, unique
        ID, IP address, OS, browser type, etc.
      </h4>
      <h4>Information from Third-Party Social Media Services</h4>
      <h4>The Company allows You to create an account and log in through the following Third-party Social Media Services:</h4>
      <ul role="list" className="list">
        <li>Discord</li>
      </ul>
      <h4>
        If You register via these services, We may collect information already associated with that account (name, email, activities, contact
        list). You may choose to share additional data; by doing so you permit us to use, share, and store it per this policy.
      </h4>
      <h4>Tracking Technologies and Cookies</h4>
      <h4>
        We use Cookies and similar tracking technologies (beacons, tags, scripts) to track activity and store information. Technologies may
        include:
      </h4>
      <ul role="list">
        <li>
          <strong>Cookies or Browser Cookies.</strong> You can refuse Cookies via browser settings, but some services may fail without them.
        </li>
        <li>
          <strong>Web Beacons.</strong> Small electronic files that allow us to count users, verify system integrity, etc.
        </li>
      </ul>
      <h4>
        Cookies can be &quot;Persistent&quot; or &quot;Session&quot;. Persistent remain after going offline; Session are deleted when the
        browser closes. We use both types for purposes detailed below:
      </h4>
      <ul role="list" className="list-2">
        <li>
          <strong>Necessary / Essential Cookies</strong> (Session) – enable core functionality.
        </li>
        <li>
          <strong>Cookies Policy / Notice Acceptance Cookies</strong> (Persistent) – remember your consent.
        </li>
        <li>
          <strong>Functionality Cookies</strong> (Persistent) – remember preferences for a personalized experience.
        </li>
      </ul>
      <h4>Use of Your Personal Data</h4>
      <h4>The Company may use Personal Data for the following purposes:</h4>
      <ul role="list" className="list">
        <li>
          <strong>To provide and maintain our Service,</strong> including usage monitoring.
        </li>
        <li>
          <strong>To manage Your Account:</strong> registration and access to functionalities.
        </li>
        <li>
          <strong>For the performance of a contract:</strong> development and execution of purchase or other agreements.
        </li>
        <li>
          <strong>To contact You:</strong> via email, phone, SMS, push notifications regarding updates or informative communications.
        </li>
        <li>
          <strong>To provide You</strong> with news, special offers and general information about similar goods/services.
        </li>
        <li>
          <strong>To manage Your requests:</strong> attend and manage requests to Us.
        </li>
        <li>
          <strong>For business transfers:</strong> evaluate or conduct mergers, sales, etc.
        </li>
        <li>
          <strong>For other purposes:</strong> data analysis, usage trends, campaign effectiveness, improve Service/products/marketing.
        </li>
      </ul>
      <h4>We may share Your personal information in these situations:</h4>
      <ul role="list">
        <li>
          <strong>With Service Providers:</strong> to monitor/analyze usage, to contact You.
        </li>
        <li>
          <strong>For business transfers:</strong> during mergers, sales, financing, acquisitions.
        </li>
        <li>
          <strong>With Affiliates:</strong> requiring them to honor this policy.
        </li>
        <li>
          <strong>With business partners:</strong> to offer certain products/services.
        </li>
        <li>
          <strong>With other users:</strong> when you interact publicly, e.g., via social media integrations.
        </li>
        <li>
          <strong>With Your consent:</strong> for any other purpose.
        </li>
      </ul>
      <h4>Retention of Your Personal Data</h4>
      <h4>
        We retain Personal Data as long as necessary for the purposes outlined, including legal obligations, dispute resolution, and policy
        enforcement.
      </h4>
      <h4>Transfer of Your Personal Data</h4>
      <h4>
        Data may be transferred to and maintained on computers outside your jurisdiction. We ensure adequate controls are in place before any
        transfer occurs.
      </h4>
      <h4>Delete Your Personal Data</h4>
      <h4>
        You can request deletion of Personal Data. Some information may be required for legal obligations. You may manage your info via
        account settings or by contacting us.
      </h4>
      <h4>Disclosure of Your Personal Data</h4>
      <h4>Business Transactions &amp; Legal Requirements</h4>
      <ul role="list" className="list">
        <li>Comply with legal obligations</li>
        <li>Protect Company rights/property</li>
        <li>Prevent wrongdoing</li>
        <li>Protect personal safety</li>
        <li>Protect against legal liability</li>
      </ul>
      <h4>Security of Your Personal Data</h4>
      <h4>
        We use commercially acceptable means to protect Personal Data but cannot guarantee absolute security due to limitations of the
        internet/storage.
      </h4>
      <h4>Children&apos;s Privacy</h4>
      <h4>
        We do not knowingly collect data from anyone under 13. If you believe a child provided data, contact us; we will remove it where
        required.
      </h4>
      <h4>Links to Other Websites</h4>
      <h4>
        Our Service may contain links to third-party sites. We are not responsible for their policies; review each site&apos;s privacy
        policy.
      </h4>
      <h4>Changes to this Privacy Policy</h4>
      <h4>
        We may update this policy from time to time and will post the new version with an updated &quot;Last updated&quot; date.
      </h4>
      <h4>Contact Us</h4>
      <h4>If you have any questions about this Privacy Policy, contact us:</h4>
      <ul role="list" className="list">
        <li>By email: info@massa.foundation</li>
      </ul>
    </div>
  )
}

export default PrivacyPolicy

